[package]
name = "vcd-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.14"
native-dialog = "0.9"
vcd-statistical-analysis = { path = "../vcd-statistical-analysis" }
logger = { path = "../logger" }

[build-dependencies]
slint-build = "1.14"
