[package]
name = "vcd"
version = "0.1.0"
edition = "2021"

[dependencies]
vcd-statistical-analysis = { path = "../vcd-statistical-analysis" }
logger = { path = "../logger" }
clap = { version = "4.5.53", features = ["derive"] }
clap_derive = "4.5"
